# -*- mode: ruby -*-
# vi: set ft=ruby :
# Main inspiration -> https://gitlab.com/xavki/presentations-kubernetes/-/blob/master/Vagrantfile

# Provisionning

$script = <<-'SCRIPT'
echo "These are my \"quotes\"! I am provisioning my guest."

# Update distro and add prerequisties

sudo bash -c "echo 'fastestmirror=1' >> /etc/dnf/dnf.conf"
sudo dnf clean all
sudo dnf install -y epel-release
sudo dnf update -y
sudo dnf install -y neovim vim nano fish zsh python3-neovim

# Disable SELinux

sudo sed -i "s|enforcing|disabled|g"  /etc/selinux/config
sudo setenforce 0

# OS preparation

systemctl disable firewalld --now

date > /etc/vagrant_provisioned_at
SCRIPT

# Box config

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../", "/vagrant", type: "rsync",
    rsync__exclude: [".git/", ".pre-commit-config.yaml"]

  # Master node

  config.vm.define "kubmaster" do |kubmaster|
    kubmaster.vm.box = "rockylinux/9"
    kubmaster.vm.box_url = "rockylinux/9"
    kubmaster.vm.hostname = 'kubmaster'

    kubmaster.vm.provision "shell", inline: $script

    kubmaster.vm.network :private_network, ip: "192.168.56.101"
  end

  # Worker node

  config.vm.define "kubworker" do |kubnode|
    kubnode.vm.box = "rockylinux/9"
    kubnode.vm.box_url = "rockylinux/9"
    kubnode.vm.hostname = 'kubnode'
    
    kubnode.vm.provision "shell", inline: $script

    kubnode.vm.network :private_network, ip: "192.168.56.102"
  end
end
