apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard
  namespace: default
data:
  FOO: HelloWorld
  BAR: "Kubernetes is cool, isn't it ? :)"
  k8s.md: |
    **💙 K8S 💙**

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard-cm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard-cm
  template:
    metadata:
      labels:
        app: kuard-cm
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:blue
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
              name: web
          env:
            - name: FOO
              valueFrom:
                configMapKeyRef:
                  name: kuard
                  key: FOO
            - name: BAR
              valueFrom:
                configMapKeyRef:
                  name: kuard
                  key: BAR
          volumeMounts:
            - name: kuard-config-volume
              mountPath: /config
      volumes:
        - name: kuard-config-volume
          configMap:
            name: kuard
