name: Presentation

on:
  release:
    types: [published]

  push:
    branches: [main]
    paths:
      - "slidev/**"
      - ".github/**"

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "slidev/**"
      - ".github/**"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            acess-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: cd slidev/ && nix develop .#slidev --command pnpm install

      - name: Build
        run: cd slidev/ && nix develop .#slidev --command slidev build --base K8SPresentation

      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
